services:

    adminer:
        container_name: adminer_skarp
        image: adminer
        restart: always
        ports:
            - 3500:8080

    db:
        image: postgres
        restart: on-failure
        container_name: postgres_skarp
        environment:
            POSTGRES_USER: bob
            POSTGRES_PASSWORD: boob
            POSTGRES_DB: skarpa_jobb
            POSTGRES_HOST_AUTH_METHOD: password
        ports: 
            - 5432:5432