services:

    adminer:
        image: adminer
        restart: always
        ports:
            - 3500:8080

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: bob
            POSTGRES_PASSWORD: bob
            POSTGRES_DB: jobs
            POSTGRES_HOST_AUTH_METHOD: trust

    
    